workflows:
  ios-release:
    name: iOS Release (TestFlight)

    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: com.phuem.cabinet_checker
      groups:
        - app_store_credentials
      ios_signing:
        distribution_type: app_store
        bundle_identifier: $BUNDLE_ID

    integrations:
      app_store_connect: codemagic

    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Build IPA (development)
        script: |
          flutter build ipa \
            --release \
            --export-method development

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true